//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertizementSetting
    {
        public System.Guid ID { get; set; }
        public string Title_en { get; set; }
        public string Title_jp { get; set; }
        public string Title_kr { get; set; }
        public string Title_fr { get; set; }
        public string Title_cn { get; set; }
        public string Title_tl { get; set; }
        public string Description_en { get; set; }
        public string Description_jp { get; set; }
        public string Description_kr { get; set; }
        public string Description_fr { get; set; }
        public string Description_cn { get; set; }
        public string Description_tl { get; set; }
        public Nullable<System.DateTime> ValidDateTime { get; set; }
        public byte[] BackgroundImage { get; set; }
        public string BackgroundColor { get; set; }
        public Nullable<long> ApplicationID { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string BackgroundImageFile { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
