//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBusinessInformation
    {
        public System.Guid ID { get; set; }
        public System.Guid CompanyID { get; set; }
        public string BusinessInfo_en { get; set; }
        public string BusinessInfo_jp { get; set; }
        public string BusinessInfo_kr { get; set; }
        public string BusinessInfo_cn { get; set; }
        public string BusinessInfo_fr { get; set; }
        public string BusinessInfo_tl { get; set; }
        public string CompanyInfo_en { get; set; }
        public string CompanyInfo_jp { get; set; }
        public string CompanyInfo_kr { get; set; }
        public string CompanyInfo_cn { get; set; }
        public string CompanyInfo_fr { get; set; }
        public string CompanyInfo_tl { get; set; }
        public string Impression_en { get; set; }
        public string Impression_jp { get; set; }
        public string Impression_kr { get; set; }
        public string Impression_cn { get; set; }
        public string Impression_fr { get; set; }
        public string Impression_tl { get; set; }
        public string SiteFindIDs { get; set; }
        public string SpecialtiyName { get; set; }
        public Nullable<System.Guid> ServiceID { get; set; }
        public Nullable<System.Guid> SpecialityID { get; set; }
        public Nullable<System.Guid> Language1ID { get; set; }
        public Nullable<System.Guid> Language2ID { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<long> Price { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Master_CompanyBusinessService Master_CompanyBusinessService { get; set; }
        public virtual Master_CompanyBusinessSpeciality Master_CompanyBusinessSpeciality { get; set; }
        public virtual Master_Language Master_Language { get; set; }
        public virtual Master_Language Master_Language1 { get; set; }
    }
}
