//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBusinessHistory
    {
        public System.Guid ID { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<int> AppointmentType { get; set; }
        public Nullable<int> AppointmentResultID { get; set; }
        public string Comment_en { get; set; }
        public string Comment_jp { get; set; }
        public string Comment_kr { get; set; }
        public string Comment_cn { get; set; }
        public string Comment_fr { get; set; }
        public string Comment_tl { get; set; }
        public string OrderSystem_en { get; set; }
        public string OrderSystem_jp { get; set; }
        public string OrderSystem_kr { get; set; }
        public string OrderSystem_cn { get; set; }
        public string OrderSystem_fr { get; set; }
        public string OrderSystem_tl { get; set; }
        public string BusinessType_en { get; set; }
        public string BusinessType_jp { get; set; }
        public string BusinessType_kr { get; set; }
        public string BusinessType_cn { get; set; }
        public string BusinessType_fr { get; set; }
        public string BusinessType_tl { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<long> CapitalStock { get; set; }
        public Nullable<long> SalesScale { get; set; }
        public string CEO { get; set; }
        public string BranchInfo_en { get; set; }
        public string BranchInfo_jp { get; set; }
        public string BranchInfo_kr { get; set; }
        public string BranchInfo_cn { get; set; }
        public string BranchInfo_fr { get; set; }
        public string BranchInfo_tl { get; set; }
        public string ImpressionOfCompany_en { get; set; }
        public string ImpressionOfCompany_jp { get; set; }
        public string ImpressionOfCompany_kr { get; set; }
        public string ImpressionOfCompany_cn { get; set; }
        public string ImpressionOfCompany_fr { get; set; }
        public string ImpressionOfCompany_tl { get; set; }
    }
}
