//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.EstimationRequestHistories = new HashSet<EstimationRequestHistory>();
            this.Company_AgencyPrice = new HashSet<Company_AgencyPrice>();
            this.Company_Department = new HashSet<Company_Department>();
            this.Company_TransproPartner = new HashSet<Company_TransproPartner>();
            this.CompanyIndustryClassifications = new HashSet<CompanyIndustryClassification>();
            this.OrderEvaluationByCustomers = new HashSet<OrderEvaluationByCustomer>();
            this.EmailDeliverySettings = new HashSet<EmailDeliverySetting>();
            this.Estimations = new HashSet<Estimation>();
            this.Order_Web = new HashSet<Order_Web>();
            this.Orders = new HashSet<Order>();
            this.OrderAppointedToStaff_Web = new HashSet<OrderAppointedToStaff_Web>();
            this.OrderRequestedToStaff_Web = new HashSet<OrderRequestedToStaff_Web>();
        }
    
        public System.Guid ID { get; set; }
        public long RegistrationID { get; set; }
        public Nullable<int> CompanyTypeID { get; set; }
        public Nullable<int> RegistrationType { get; set; }
        public Nullable<long> CompanyLocationID { get; set; }
        public Nullable<int> CompanyRegPurposeID { get; set; }
        public Nullable<System.Guid> CompanyTradingOfficeID { get; set; }
        public string RegistrationNo { get; set; }
        public string ClientID { get; set; }
        public bool IsPartner { get; set; }
        public Nullable<long> PartnerServiceTypeID { get; set; }
        public bool IsSubcontactual { get; set; }
        public string Name_Local { get; set; }
        public string Name_Global { get; set; }
        public string WebSiteURL { get; set; }
        public string RepresentativeDirector_en { get; set; }
        public string RepresentativeDirector_jp { get; set; }
        public string RepresentativeDirector_kr { get; set; }
        public string RepresentativeDirector_cn { get; set; }
        public string RepresentativeDirector_fr { get; set; }
        public string RepresentativeDirector_tl { get; set; }
        public Nullable<long> Capital { get; set; }
        public Nullable<System.DateTime> EstablishedDate { get; set; }
        public string BusinesClassification { get; set; }
        public string TransactionCategory { get; set; }
        public string TransactionNotes { get; set; }
        public string TransactionRecords { get; set; }
        public string FilesWithInvoice { get; set; }
        public string IntroducedBy { get; set; }
        public Nullable<bool> IsStopTrading { get; set; }
        public Nullable<bool> IsSharedRecord { get; set; }
        public string BusinessSummary { get; set; }
        public string CompanyIntroduction { get; set; }
        public string CompanyImpression { get; set; }
        public Nullable<System.DateTime> SalesRecordRegDate { get; set; }
        public Nullable<int> ActivityTypeID { get; set; }
        public Nullable<int> ActivityResultID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string ClientMemberName { get; set; }
        public Nullable<System.Guid> EmployeeMemberID { get; set; }
        public string Comment_en { get; set; }
        public string Comment_jp { get; set; }
        public string Comment_kr { get; set; }
        public string Comment_fr { get; set; }
        public string Comment_tl { get; set; }
        public string Comment_cn { get; set; }
        public Nullable<int> PaymentWayID { get; set; }
        public Nullable<long> BankTradingOfficeID { get; set; }
        public string BillingPostCode { get; set; }
        public string BillingAddress { get; set; }
        public string BilligPersonDesignation { get; set; }
        public string BillingPersonName { get; set; }
        public Nullable<bool> IsAllowPaymentAfterDelivery { get; set; }
        public string AffiliateCode { get; set; }
        public Nullable<int> AffiliateTypeID { get; set; }
        public string AffiliateCompanyName { get; set; }
        public Nullable<System.DateTime> AffiliateUpdateDate { get; set; }
        public string Note_en { get; set; }
        public string Note_jp { get; set; }
        public string Note_kr { get; set; }
        public string Note_fr { get; set; }
        public string Note_tl { get; set; }
        public string Note_cn { get; set; }
        public Nullable<bool> IsCampaignEmail { get; set; }
        public Nullable<bool> IsOrderShowEnable { get; set; }
        public Nullable<System.Guid> DivisionID { get; set; }
        public Nullable<System.Guid> CorporateDivisionID { get; set; }
        public Nullable<long> OriginCountryID { get; set; }
        public bool IsCompanyAgent { get; set; }
        public string CorporateNo { get; set; }
        public Nullable<System.Guid> businessClassificationID { get; set; }
        public Nullable<System.DateTime> DateOfPayment { get; set; }
        public Nullable<bool> IsBillingMonthly { get; set; }
        public string MainPhoto { get; set; }
        public string Logo { get; set; }
        public string EmployeeName_en { get; set; }
        public string EmployeeName_jp { get; set; }
        public string EmployeeName_kr { get; set; }
        public string EmployeeName_cn { get; set; }
        public string EmployeeName_fr { get; set; }
        public string EmployeeName_tl { get; set; }
        public string BranchName_en { get; set; }
        public string BranchName_jp { get; set; }
        public string BranchName_kr { get; set; }
        public string BranchName_cn { get; set; }
        public string BranchName_fr { get; set; }
        public string BranchName_tl { get; set; }
        public string TradingNote { get; set; }
        public string TradingRecord { get; set; }
        public System.Guid BankID { get; set; }
        public System.Guid BankBranchID { get; set; }
        public long BankAccountTypeID { get; set; }
        public string PrivateCompanyName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Name_en { get; set; }
        public string Name_jp { get; set; }
        public string Name_kr { get; set; }
        public string Name_cn { get; set; }
        public string Name_fr { get; set; }
        public string Name_tl { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string Fax { get; set; }
        public string PostalCode { get; set; }
        public string Address1_en { get; set; }
        public string Address1_jp { get; set; }
        public string Address1_kr { get; set; }
        public string Address1_cn { get; set; }
        public string Address1_fr { get; set; }
        public string Address1_tl { get; set; }
        public string Address2_en { get; set; }
        public string Address2_jp { get; set; }
        public string Address2_kr { get; set; }
        public string Address2_cn { get; set; }
        public string Address2_fr { get; set; }
        public string Address2_tl { get; set; }
        public Nullable<bool> IsRecieveEmail { get; set; }
        public Nullable<bool> IsPostTransactionAllowed { get; set; }
        public Nullable<int> NoteDeliveryTypeID { get; set; }
        public Nullable<int> InvoiceDeliveryTypeID { get; set; }
        public Nullable<int> RecieptDeliveryTypeID { get; set; }
        public bool IsNoteByEmail { get; set; }
        public bool IsInvoiceByEmail { get; set; }
        public bool IsRecieptByEmail { get; set; }
        public bool IsNoteOuputPaper { get; set; }
        public bool IsInvoiceOutputPaper { get; set; }
        public bool IsRecieptOutputPaper { get; set; }
        public Nullable<long> ApplicationId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationRequestHistory> EstimationRequestHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_AgencyPrice> Company_AgencyPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_Department> Company_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_TransproPartner> Company_TransproPartner { get; set; }
        public virtual Master_BranchOffice Master_BranchOffice { get; set; }
        public virtual Master_DeliveryMethod Master_DeliveryMethod { get; set; }
        public virtual Master_DeliveryMethod Master_DeliveryMethod1 { get; set; }
        public virtual Master_DeliveryMethod Master_DeliveryMethod2 { get; set; }
        public virtual Master_PartnerServiceType Master_PartnerServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyIndustryClassification> CompanyIndustryClassifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEvaluationByCustomer> OrderEvaluationByCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailDeliverySetting> EmailDeliverySettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estimation> Estimations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Web> Order_Web { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAppointedToStaff_Web> OrderAppointedToStaff_Web { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRequestedToStaff_Web> OrderRequestedToStaff_Web { get; set; }
    }
}
