//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyIndustryClassification
    {
        public System.Guid ID { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> IndustryClassificationID { get; set; }
        public Nullable<System.Guid> IndustryClassificationItemID { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Master_CompanyIndustryClassification Master_CompanyIndustryClassification { get; set; }
        public virtual Master_CompanyIndustryClassificationItem Master_CompanyIndustryClassificationItem { get; set; }
    }
}
