//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyAgentDesignation
    {
        public System.Guid ID { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> AgentDesignationID { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    
        public virtual Master_AgentFreeDesignation Master_AgentFreeDesignation { get; set; }
    }
}
