//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCooperativeInfo
    {
        public System.Guid ID { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<bool> IsTranslationCompany { get; set; }
        public Nullable<long> ChargingRate { get; set; }
        public Nullable<long> PriceGroup1 { get; set; }
        public Nullable<long> PriceGroup2 { get; set; }
        public Nullable<long> PriceGroup3 { get; set; }
        public Nullable<long> PriceGroup4 { get; set; }
    }
}
