//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_AgencyPrice
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
        public Nullable<int> EstimationTypeID { get; set; }
        public Nullable<System.Guid> SourceLanguageID { get; set; }
        public Nullable<System.Guid> DestinationLanguageID { get; set; }
        public Nullable<System.Guid> SpecializedFieldID { get; set; }
        public Nullable<long> Unit { get; set; }
        public Nullable<int> PriceCalculationOnID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public bool IsDelete { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Master_EstimationSpecializedField Master_EstimationSpecializedField { get; set; }
        public virtual Master_EstimationType Master_EstimationType { get; set; }
        public virtual Master_Language Master_Language { get; set; }
        public virtual Master_Language Master_Language1 { get; set; }
    }
}
