//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyShare
    {
        public long ID { get; set; }
        public int ShareType { get; set; }
        public string ShareName { get; set; }
        public string ShareNicName { get; set; }
        public Nullable<decimal> ShareRate { get; set; }
    }
}
