//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTradingCategory
    {
        public System.Guid ID { get; set; }
        public System.Guid CompanyID { get; set; }
        public Nullable<System.Guid> TradingCategoryID { get; set; }
        public Nullable<System.Guid> TradingCategoryItemID { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    
        public virtual Master_CompanyTradingCategory Master_CompanyTradingCategory { get; set; }
        public virtual Master_CompanyTradingCategoryItem Master_CompanyTradingCategoryItem { get; set; }
    }
}
