//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactU
    {
        public System.Guid ID { get; set; }
        public long RegistrationID { get; set; }
        public string Name_en { get; set; }
        public string Name_jp { get; set; }
        public string Name_fr { get; set; }
        public string Name_kr { get; set; }
        public string Name_cn { get; set; }
        public string Name_tl { get; set; }
        public string DivisionName { get; set; }
        public string TelNumber { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Comment_en { get; set; }
        public string Comment_jp { get; set; }
        public string Comment_fr { get; set; }
        public string Comment_kr { get; set; }
        public string Comment_cn { get; set; }
        public string Comment_tl { get; set; }
        public Nullable<long> ApplicationID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public Nullable<long> RepliedBy { get; set; }
        public bool IsReplied { get; set; }
        public string CompanyName { get; set; }
        public string CompanyURLOne { get; set; }
        public string CompanyURLTwo { get; set; }
        public string PrefferedWebSystem { get; set; }
    
        public virtual UserInformation UserInformation { get; set; }
    }
}
