//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailDeliverySetting
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<System.Guid> StaffID { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public bool IsBusinessHour { get; set; }
        public bool IsInterval { get; set; }
        public bool IsAnyTime { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public bool IsArrangedNotice { get; set; }
        public bool IsDeliveryNotice { get; set; }
        public bool IsTranslatorRequest { get; set; }
        public bool IsMessageNotice { get; set; }
        public bool IsTranslatiorConfirmed { get; set; }
        public bool IsPaymentNotification { get; set; }
        public Nullable<long> ApplicationId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
