//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public long ID { get; set; }
        public string Name_en { get; set; }
        public string Name_jp { get; set; }
        public string Name_kr { get; set; }
        public string Name_cn { get; set; }
        public string Name_fr { get; set; }
        public string Name_tl { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string Subject_en { get; set; }
        public string Subject_jp { get; set; }
        public string Subject_kr { get; set; }
        public string Subject_cn { get; set; }
        public string Subject_fr { get; set; }
        public string Subject_tl { get; set; }
        public string Body_en { get; set; }
        public string Body_jp { get; set; }
        public string Body_kr { get; set; }
        public string Body_cn { get; set; }
        public string Body_fr { get; set; }
        public string Body_tl { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
