//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Estimations = new HashSet<Estimation>();
            this.Estimations1 = new HashSet<Estimation>();
            this.Estimations2 = new HashSet<Estimation>();
            this.Estimations3 = new HashSet<Estimation>();
            this.Estimations4 = new HashSet<Estimation>();
            this.Estimations5 = new HashSet<Estimation>();
            this.EstimationApprovals = new HashSet<EstimationApproval>();
        }
    
        public System.Guid ID { get; set; }
        public long RegistrationID { get; set; }
        public string EmployeeID { get; set; }
        public long CountryID { get; set; }
        public System.Guid DepartmentID { get; set; }
        public Nullable<System.Guid> BranchOfficeID { get; set; }
        public Nullable<long> EmployeeTypeID { get; set; }
        public Nullable<long> ApplicationID { get; set; }
        public string Name_en { get; set; }
        public string Name_jp { get; set; }
        public string Name_kr { get; set; }
        public string Name_cn { get; set; }
        public string Name_fr { get; set; }
        public string Name_tl { get; set; }
        public string Password { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public Nullable<int> AttendanceDay { get; set; }
        public string ClockInTime { get; set; }
        public string ClockOutTime { get; set; }
        public string SkypeID { get; set; }
        public string SkypePassword { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsResponsiblePerson { get; set; }
        public string HomeAddress_en { get; set; }
        public string HomeAddress_jp { get; set; }
        public string HomeAddress_kr { get; set; }
        public string HomeAddress_cn { get; set; }
        public string HomeAddress_fr { get; set; }
        public string HomeAddress_tl { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string PCEmail { get; set; }
        public string MobileEmail { get; set; }
        public string Sns_one { get; set; }
        public string Sns_two { get; set; }
        public System.Guid BankID { get; set; }
        public System.Guid BankBranchID { get; set; }
        public long BankAccountTypeID { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountName { get; set; }
        public string Photo { get; set; }
        public string Signature { get; set; }
        public string Institute_en { get; set; }
        public string Institute_jp { get; set; }
        public string Institute_kr { get; set; }
        public string Institute_cn { get; set; }
        public string Institute_fr { get; set; }
        public string Institute_tl { get; set; }
        public string AcademicQualification { get; set; }
        public System.Guid Language_one { get; set; }
        public Nullable<System.Guid> Language_two { get; set; }
        public Nullable<System.Guid> Language_three { get; set; }
        public string SelfIntroduction_en { get; set; }
        public string SelfIntroduction_jp { get; set; }
        public string SelfIntroduction_kr { get; set; }
        public string SelfIntroduction_fr { get; set; }
        public string SelfIntroduction_tl { get; set; }
        public string SelfIntroduction_cn { get; set; }
        public string Note_en { get; set; }
        public string Note_jp { get; set; }
        public string Note_kr { get; set; }
        public string Note_fr { get; set; }
        public string Note_tl { get; set; }
        public string Note_cn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool Active { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Master_BranchOffice Master_BranchOffice { get; set; }
        public virtual Master_BranchOffice Master_BranchOffice1 { get; set; }
        public virtual Master_Country Master_Country { get; set; }
        public virtual Master_Department Master_Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estimation> Estimations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estimation> Estimations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estimation> Estimations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estimation> Estimations3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estimation> Estimations4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Estimation> Estimations5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationApproval> EstimationApprovals { get; set; }
    }
}
