//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorReportWeb
    {
        public long ID { get; set; }
        public Nullable<long> ApplicationID { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string ErrorPageUrl { get; set; }
        public string ErrorMessage { get; set; }
        public string OsName { get; set; }
        public string BrowserVersion { get; set; }
        public string Reproducibility { get; set; }
        public string ErrorDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
