//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public System.Guid ID { get; set; }
        public long UserID { get; set; }
        public string Component { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual UserInformation UserInformation { get; set; }
    }
}
