//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimationNarrationExpense
    {
        public System.Guid ID { get; set; }
        public Nullable<int> TransportationUnitprice { get; set; }
        public Nullable<int> TransportationNumberOfPersons { get; set; }
        public Nullable<int> TransportationNumberOfDays { get; set; }
        public Nullable<int> TransportationTotal { get; set; }
        public Nullable<int> AccomodationUnitprice { get; set; }
        public Nullable<int> AccomodationNumberOfPersons { get; set; }
        public Nullable<int> AccomodationNumberOfDays { get; set; }
        public Nullable<int> AccomodationTotal { get; set; }
        public Nullable<int> MealUnitprice { get; set; }
        public Nullable<int> MealNumberOfPersons { get; set; }
        public Nullable<int> MealNumberOfDays { get; set; }
        public Nullable<int> MealTotal { get; set; }
        public Nullable<int> AllowanceUnitprice { get; set; }
        public Nullable<int> AllowanceNumberOfPersons { get; set; }
        public Nullable<int> AllowanceNumberOfDays { get; set; }
        public Nullable<int> AllowanceTotal { get; set; }
        public Nullable<bool> TransportationExclTax { get; set; }
        public Nullable<bool> AccomodationCompleteSet { get; set; }
        public Nullable<bool> AccomodationExclTax { get; set; }
        public Nullable<bool> MealCompleteSet { get; set; }
        public Nullable<bool> MealExclTax { get; set; }
        public Nullable<bool> AllowanceCompleteSet { get; set; }
        public Nullable<bool> AllowanceExclTax { get; set; }
        public System.Guid EstimationID { get; set; }
    
        public virtual Estimation Estimation { get; set; }
    }
}
