//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estimation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estimation()
        {
            this.EstimationActions = new HashSet<EstimationAction>();
            this.EstimationApprovals = new HashSet<EstimationApproval>();
            this.EstimationCompetencies = new HashSet<EstimationCompetency>();
            this.EstimationDeliveryFileTypes = new HashSet<EstimationDeliveryFileType>();
            this.EstimationDetails = new HashSet<EstimationDetail>();
            this.EstimationFiles = new HashSet<EstimationFile>();
            this.EstimationWorkContents = new HashSet<EstimationWorkContent>();
            this.EstimationNarrationExpenses = new HashSet<EstimationNarrationExpense>();
            this.Order_StaffAllowance = new HashSet<Order_StaffAllowance>();
            this.Orders = new HashSet<Order>();
        }
    
        public System.Guid ID { get; set; }
        public long RegistrationID { get; set; }
        public string EstimationNo { get; set; }
        public Nullable<System.DateTime> InquiryDate { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<long> ApplicationID { get; set; }
        public Nullable<System.Guid> EstimateRouteID { get; set; }
        public Nullable<System.Guid> OutwardSalesID { get; set; }
        public Nullable<System.Guid> LargeSalesID { get; set; }
        public Nullable<System.Guid> SalesPersonID { get; set; }
        public Nullable<System.Guid> AssistantID { get; set; }
        public Nullable<System.Guid> CoordinatorID { get; set; }
        public Nullable<System.Guid> ApprovalID { get; set; }
        public System.Guid ClientID { get; set; }
        public Nullable<System.Guid> ClientDepartmentID { get; set; }
        public System.Guid TradingID { get; set; }
        public Nullable<System.Guid> ProjectID { get; set; }
        public Nullable<System.Guid> TeamID { get; set; }
        public Nullable<bool> IsCompanyPrivate { get; set; }
        public Nullable<int> ClientStatus { get; set; }
        public Nullable<System.Guid> SubSpecializedFieldID { get; set; }
        public Nullable<System.Guid> BusinessCategoryID { get; set; }
        public string ClientPersonInCharge { get; set; }
        public string ClientEmailCC { get; set; }
        public string ClientAddress_en { get; set; }
        public string ClientAddress_jp { get; set; }
        public string ClientAddress_kr { get; set; }
        public string ClientAddress_cn { get; set; }
        public string ClientAddress_fr { get; set; }
        public string ClientAddress_tl { get; set; }
        public string ClientContactNo { get; set; }
        public string ClientFax { get; set; }
        public string BillingCompanyName_en { get; set; }
        public string BillingCompanyName_jp { get; set; }
        public string BillingCompanyName_kr { get; set; }
        public string BillingCompanyName_cn { get; set; }
        public string BillingCompanyName_fr { get; set; }
        public string BillingCompanyName_tl { get; set; }
        public string BillingTo { get; set; }
        public string BillingEmailCC { get; set; }
        public string BillingAddress_en { get; set; }
        public string BillingAddress_jp { get; set; }
        public string BillingAddress_kr { get; set; }
        public string BillingAddress_cn { get; set; }
        public string BillingAddress_fr { get; set; }
        public string BillingAddress_tl { get; set; }
        public string BillingContactNo { get; set; }
        public string BillingFax { get; set; }
        public Nullable<bool> IsPostingBill { get; set; }
        public string PaymentTerms { get; set; }
        public string DeliveryCompanyName_en { get; set; }
        public string DeliveryCompanyName_jp { get; set; }
        public string DeliveryCompanyName_kr { get; set; }
        public string DeliveryCompanyName_cn { get; set; }
        public string DeliveryCompanyName_fr { get; set; }
        public string DeliveryCompanyName_tl { get; set; }
        public string DeliveryTo { get; set; }
        public string DeliveryEmailCC { get; set; }
        public string DeliveryAddress_en { get; set; }
        public string DeliveryAddress_jp { get; set; }
        public string DeliveryAddress_kr { get; set; }
        public string DeliveryAddress_cn { get; set; }
        public string DeliveryAddress_fr { get; set; }
        public string DeliveryAddress_tl { get; set; }
        public string DeliveryContactNo { get; set; }
        public string DeliveryFax { get; set; }
        public string DeliveryInstruction { get; set; }
        public string RemarksCoordinatorType { get; set; }
        public Nullable<long> CurrencyID { get; set; }
        public Nullable<bool> IsProspect { get; set; }
        public Nullable<bool> IsUndisclosed { get; set; }
        public int EstimationType { get; set; }
        public int EstimationStatus { get; set; }
        public System.Guid SpecializedFieldID { get; set; }
        public Nullable<bool> IsInternalPurpose { get; set; }
        public Nullable<bool> IsExternalPurpose { get; set; }
        public Nullable<bool> IsPrintPurpose { get; set; }
        public Nullable<bool> IsWebPurpose { get; set; }
        public Nullable<bool> IsOtherPurpose { get; set; }
        public string OtherPurposeText { get; set; }
        public Nullable<bool> PriorityQuality { get; set; }
        public Nullable<bool> PriorityPrice { get; set; }
        public Nullable<bool> PriorityDelivery { get; set; }
        public Nullable<bool> PriorityTender { get; set; }
        public Nullable<bool> KnownByGoogle { get; set; }
        public Nullable<bool> KnownByYahoo { get; set; }
        public Nullable<bool> KnownByEmail { get; set; }
        public Nullable<bool> KnownByBing { get; set; }
        public Nullable<bool> KnownByOthers { get; set; }
        public string KnownOtherText { get; set; }
        public Nullable<System.DateTime> FinalDeliveryDate { get; set; }
        public Nullable<System.DateTime> FirstDeliveryDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string AttachedMaterialFileName { get; set; }
        public string AttachedMaterialDownloadURL { get; set; }
        public string CoordinatorNotes_en { get; set; }
        public string CoordinatorNotes_jp { get; set; }
        public string CoordinatorNotes_kr { get; set; }
        public string CoordinatorNotes_cn { get; set; }
        public string CoordinatorNotes_fr { get; set; }
        public string CoordinatorNotes_tl { get; set; }
        public string Remarks_en { get; set; }
        public string Remarks_jp { get; set; }
        public string Remarks_kr { get; set; }
        public string Remarks_cn { get; set; }
        public string Remarks_fr { get; set; }
        public string Remarks_tl { get; set; }
        public Nullable<bool> IsRemarksHideInPDF { get; set; }
        public Nullable<bool> IsOrderReceived { get; set; }
        public Nullable<decimal> DiscountTotal { get; set; }
        public Nullable<decimal> AverageUnitPrice { get; set; }
        public Nullable<decimal> ActualUnitPrice { get; set; }
        public bool IsDeleted { get; set; }
        public string PurposeDetails { get; set; }
        public string OrderTitle { get; set; }
        public long IssuedByTranslator { get; set; }
        public long IssuedByCompany { get; set; }
        public Nullable<decimal> PriceCertification { get; set; }
        public string OtherItemName_en { get; set; }
        public string OtherItemName_jp { get; set; }
        public string OtherItemName_kr { get; set; }
        public string OtherItemName_cn { get; set; }
        public string OtherItemName_fr { get; set; }
        public string OtherItemName_tl { get; set; }
        public Nullable<decimal> OtherItemUnitPrice { get; set; }
        public Nullable<int> OtherItemNumber { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
        public Nullable<decimal> TaxEstimation { get; set; }
        public Nullable<decimal> QuotationInclTax { get; set; }
        public Nullable<decimal> QuotationExclTax { get; set; }
        public Nullable<decimal> ConsumptionOnTax { get; set; }
        public Nullable<decimal> ExcludedTaxCost { get; set; }
        public Nullable<bool> IsCampaign { get; set; }
        public Nullable<bool> IsSpecialPrice { get; set; }
        public Nullable<bool> IsSpecialDeal { get; set; }
        public Nullable<decimal> SubtotalAfterDiscount { get; set; }
        public Nullable<decimal> QuotationTotalInclTax { get; set; }
        public Nullable<decimal> QuotationTotalExclTax { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<bool> IsPerformance { get; set; }
        public Nullable<bool> IsPrice { get; set; }
        public Nullable<bool> IsAccuracy { get; set; }
        public Nullable<bool> IsLocal { get; set; }
        public Nullable<decimal> ExpensePriceInTax { get; set; }
        public Nullable<decimal> GrossProfitRate { get; set; }
        public Nullable<decimal> TotalPriceExTax { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public Nullable<decimal> ConsumptionTax { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public Nullable<decimal> TotalWithoutTax { get; set; }
        public Nullable<decimal> TotalWithTax { get; set; }
        public string MenuScript { get; set; }
        public string QuotationNotes_en { get; set; }
        public string QuotationNotes_cn { get; set; }
        public string QuotationNotes_jp { get; set; }
        public string QuotationNotes_kr { get; set; }
        public string QuotationNotes_fr { get; set; }
        public string QuotationNotes_tl { get; set; }
        public bool ReturnDocument { get; set; }
        public bool AddTimestampInSubtitles { get; set; }
        public bool IsTemporaryRegistration { get; set; }
        public bool IsPromotion { get; set; }
        public bool IsSpecialPayment { get; set; }
        public bool IsPastComplaint { get; set; }
        public bool IsExpertise { get; set; }
        public bool IsOnGoingTask { get; set; }
        public bool IsOverseas { get; set; }
        public bool IsJapan { get; set; }
        public Nullable<long> CountryID { get; set; }
        public Nullable<bool> KnownByIntroduction { get; set; }
        public string KnownIntroductionText { get; set; }
        public Nullable<long> UnitID { get; set; }
        public Nullable<bool> IsContentAll { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual Employee Employee4 { get; set; }
        public virtual Employee Employee5 { get; set; }
        public virtual Master_Currency Master_Currency { get; set; }
        public virtual Master_EstimationRoutes Master_EstimationRoutes { get; set; }
        public virtual Master_EstimationType Master_EstimationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationAction> EstimationActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationApproval> EstimationApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationCompetency> EstimationCompetencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationDeliveryFileType> EstimationDeliveryFileTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationDetail> EstimationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationFile> EstimationFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationWorkContent> EstimationWorkContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationNarrationExpense> EstimationNarrationExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_StaffAllowance> Order_StaffAllowance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
