//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimationFile
    {
        public System.Guid ID { get; set; }
        public System.Guid EstimateID { get; set; }
        public System.Guid EstimateDetailsID { get; set; }
        public string FileName { get; set; }
        public string DownloadURL { get; set; }
        public string TranslationText { get; set; }
        public Nullable<int> WordCount { get; set; }
    
        public virtual Estimation Estimation { get; set; }
        public virtual EstimationDetail EstimationDetail { get; set; }
    }
}
