//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstimationDetail()
        {
            this.EstimationFiles = new HashSet<EstimationFile>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid EstimationID { get; set; }
        public System.Guid SourceLanguageID { get; set; }
        public System.Guid TargetLanguageID { get; set; }
        public System.Guid ServiceType { get; set; }
        public Nullable<long> DeliveryPlanID { get; set; }
        public Nullable<decimal> UnitPrice1 { get; set; }
        public Nullable<int> PageCount1 { get; set; }
        public Nullable<decimal> Discount1 { get; set; }
        public Nullable<decimal> UnitPrice2 { get; set; }
        public Nullable<int> PageCount2 { get; set; }
        public Nullable<decimal> Discount2 { get; set; }
        public Nullable<decimal> UnitPrice3 { get; set; }
        public Nullable<int> PageCount3 { get; set; }
        public Nullable<decimal> Discount3 { get; set; }
        public Nullable<decimal> UnitPrice4 { get; set; }
        public Nullable<int> PageCount4 { get; set; }
        public Nullable<decimal> Discount4 { get; set; }
        public Nullable<decimal> UnitPrice5 { get; set; }
        public Nullable<int> PageCount5 { get; set; }
        public Nullable<decimal> Discount5 { get; set; }
        public Nullable<decimal> BasicTime { get; set; }
        public Nullable<decimal> AdditionalTime { get; set; }
        public Nullable<decimal> AdditionalBasicAmount { get; set; }
        public Nullable<int> ExtraTime { get; set; }
        public Nullable<decimal> LateNightTime { get; set; }
        public Nullable<decimal> TransferTime { get; set; }
        public Nullable<decimal> BasicAmount { get; set; }
        public Nullable<decimal> ExtensionTime { get; set; }
        public Nullable<decimal> ExtensionAmount { get; set; }
        public Nullable<decimal> ExtraAmount { get; set; }
        public Nullable<decimal> LateAtNightAmount { get; set; }
        public Nullable<decimal> TransferAmount { get; set; }
        public Nullable<int> NumberOfDays { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
        public Nullable<decimal> CertificateAmount { get; set; }
        public Nullable<bool> ExcludeTax { get; set; }
        public string Contents { get; set; }
        public Nullable<decimal> LengthMinute { get; set; }
        public Nullable<bool> WithTranslation { get; set; }
        public Nullable<decimal> UnitPriceTime { get; set; }
        public Nullable<decimal> UnitPriceSubTotal { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<decimal> DiscountedPrice { get; set; }
        public Nullable<decimal> EstimationPrice { get; set; }
        public Nullable<decimal> StudioPrice { get; set; }
        public Nullable<decimal> StudioPriceTime { get; set; }
        public Nullable<decimal> EditPrice { get; set; }
        public Nullable<decimal> EditPriceTime { get; set; }
        public Nullable<decimal> StudioPriceSubTotal { get; set; }
        public Nullable<decimal> StudioPriceDiscountRate { get; set; }
        public Nullable<decimal> StudioDiscountedPrice { get; set; }
        public Nullable<decimal> TotalAfterDiscount { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> PaymentRate { get; set; }
        public Nullable<decimal> ExpectedPayment { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string StartTime { get; set; }
        public string FinishTime { get; set; }
        public Nullable<bool> IsOverseas { get; set; }
    
        public virtual Estimation Estimation { get; set; }
        public virtual Master_Language Master_Language { get; set; }
        public virtual Master_Language Master_Language1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstimationFile> EstimationFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
