//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimationAction
    {
        public System.Guid ID { get; set; }
        public System.Guid EstimationID { get; set; }
        public Nullable<System.DateTime> NextActionDate { get; set; }
        public Nullable<int> ActionType { get; set; }
        public long OperationBy { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string ActionDetails_en { get; set; }
        public string ActionDetails_jp { get; set; }
        public string ActionDetails_kr { get; set; }
        public string ActionDetails_cn { get; set; }
        public string ActionDetails_fr { get; set; }
        public string ActionDetails_tl { get; set; }
    
        public virtual Estimation Estimation { get; set; }
    }
}
