//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_UnitPriceSetting
    {
        public long ID { get; set; }
        public long UnitID { get; set; }
        public int EstimationTypeID { get; set; }
        public System.Guid SourceLanguageID { get; set; }
        public System.Guid TargetLanguageID { get; set; }
        public long CurrencyID { get; set; }
        public Nullable<decimal> GeneralUnitPrice { get; set; }
        public Nullable<decimal> SpecialUnitPrice { get; set; }
        public Nullable<decimal> PatentUnitPrice { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Master_Currency Master_Currency { get; set; }
        public virtual Master_EstimationType Master_EstimationType { get; set; }
        public virtual Master_Language Master_Language { get; set; }
        public virtual Master_Language Master_Language1 { get; set; }
        public virtual Master_Unit Master_Unit { get; set; }
    }
}
