//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_StaffJobCategoryDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Master_StaffJobCategoryDetails()
        {
            this.Staff_JobHistory = new HashSet<Staff_JobHistory>();
            this.Staff_JobHistory1 = new HashSet<Staff_JobHistory>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid JobCategoryID { get; set; }
        public string Description_en { get; set; }
        public string Description_jp { get; set; }
        public string Description_kr { get; set; }
        public string Description_cn { get; set; }
        public string Description_fr { get; set; }
        public string Description_tl { get; set; }
        public Nullable<int> SortBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual Master_StaffJobCategory Master_StaffJobCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_JobHistory> Staff_JobHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_JobHistory> Staff_JobHistory1 { get; set; }
    }
}
