//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Penalty
    {
        public System.Guid ID { get; set; }
        public Nullable<int> CategoryNo { get; set; }
        public Nullable<int> Score { get; set; }
        public string Name_en { get; set; }
        public string Name_jp { get; set; }
        public string Name_kr { get; set; }
        public string Name_cn { get; set; }
        public string Name_tl { get; set; }
        public string Name_fr { get; set; }
        public string Contents_en { get; set; }
        public string Contents_jp { get; set; }
        public string Contents_kr { get; set; }
        public string Contents_cn { get; set; }
        public string Contents_tl { get; set; }
        public string Contents_fr { get; set; }
        public string Response_en { get; set; }
        public string Response_jp { get; set; }
        public string Response_kr { get; set; }
        public string Response_cn { get; set; }
        public string Response_tl { get; set; }
        public string Response_fr { get; set; }
        public long ApplicationId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
