//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_DeliveryDocuments
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public string Name { get; set; }
        public string FileDescription { get; set; }
        public string DownloadURL { get; set; }
        public Nullable<System.DateTime> UploadDated { get; set; }
    
        public virtual Order_DeliveryDocuments Order_DeliveryDocuments1 { get; set; }
        public virtual Order_DeliveryDocuments Order_DeliveryDocuments2 { get; set; }
    }
}
