//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Web
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Web()
        {
            this.OrderEvaluationByCustomers = new HashSet<OrderEvaluationByCustomer>();
            this.OrderAppointedToStaff_Web = new HashSet<OrderAppointedToStaff_Web>();
            this.OrderRequestedToStaff_Web = new HashSet<OrderRequestedToStaff_Web>();
        }
    
        public System.Guid ID { get; set; }
        public long ApplicationID { get; set; }
        public long RegistrationID { get; set; }
        public string OrderNo { get; set; }
        public string InvoiceNo { get; set; }
        public System.Guid SourceLanguageID { get; set; }
        public System.Guid TargetLanguageID { get; set; }
        public System.Guid TranslationFieldID { get; set; }
        public Nullable<System.Guid> AssignedTranslatorID { get; set; }
        public System.Guid ClientID { get; set; }
        public long DeliveryPlanID { get; set; }
        public string DeliveryPlan { get; set; }
        public string DeliveryLevelName { get; set; }
        public long CurrencyID { get; set; }
        public Nullable<System.Guid> IntroducerID { get; set; }
        public Nullable<int> TranslationType { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
        public Nullable<long> WordCount { get; set; }
        public Nullable<int> CountType { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> TranslatorFee { get; set; }
        public Nullable<decimal> EstimatedPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> PriceAfterDiscount { get; set; }
        public Nullable<decimal> ConsumptionTax { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string CommentToTranslator { get; set; }
        public string MenuScript { get; set; }
        public string DeliveryComment { get; set; }
        public string CompanyNotes { get; set; }
        public string CommentToBcause { get; set; }
        public string ReferenceFileName { get; set; }
        public string ReferenceDownloadURL { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Master_Currency Master_Currency { get; set; }
        public virtual Master_EstimationSpecializedField Master_EstimationSpecializedField { get; set; }
        public virtual Master_Language Master_Language { get; set; }
        public virtual Master_Language Master_Language1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEvaluationByCustomer> OrderEvaluationByCustomers { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAppointedToStaff_Web> OrderAppointedToStaff_Web { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRequestedToStaff_Web> OrderRequestedToStaff_Web { get; set; }
    }
}
