//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public System.Guid ID { get; set; }
        public System.Guid OrderID { get; set; }
        public System.Guid EstimationDetailsID { get; set; }
        public Nullable<System.Guid> StaffID { get; set; }
        public Nullable<int> WorkingStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> EvaluationAmount { get; set; }
        public Nullable<decimal> PaymentAmountExcludingTax { get; set; }
        public Nullable<decimal> AgencyCommission { get; set; }
        public string ComplainDetails { get; set; }
        public Nullable<System.DateTime> RemitanceDate { get; set; }
        public Nullable<decimal> DepositAmount { get; set; }
        public Nullable<decimal> CostIncTax { get; set; }
        public Nullable<decimal> CostExclTax { get; set; }
        public Nullable<decimal> ClientBillingCost { get; set; }
        public Nullable<decimal> PaymentAmountIncludingTax { get; set; }
        public Nullable<decimal> StaffPaymentCostIncludingTax { get; set; }
        public Nullable<decimal> StaffPaymentCostExcludingTax { get; set; }
        public Nullable<decimal> TotalStaffPaymentCost { get; set; }
        public Nullable<decimal> Penalty { get; set; }
        public Nullable<bool> IsDeposited { get; set; }
        public string PlaceOfResidence { get; set; }
        public Nullable<bool> IsComplaint { get; set; }
    
        public virtual EstimationDetail EstimationDetail { get; set; }
        public virtual Order Order { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
