//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_EducationalHistory
    {
        public System.Guid ID { get; set; }
        public System.Guid StaffID { get; set; }
        public System.Guid DegreeID { get; set; }
        public System.Guid MajorSubjectID { get; set; }
        public long CountryID { get; set; }
        public System.DateTime EntryYear { get; set; }
        public System.DateTime GraduationYear { get; set; }
        public string InstituteName_en { get; set; }
        public string InstituteName_jp { get; set; }
        public string InstituteName_kr { get; set; }
        public string InstituteName_cn { get; set; }
        public string InstituteName_fr { get; set; }
        public string InstituteName_tl { get; set; }
        public string Comment_en { get; set; }
        public string Comment_jp { get; set; }
        public string Comment_kr { get; set; }
        public string Comment_cn { get; set; }
        public string Comment_fr { get; set; }
        public string Comment_tl { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual Master_Country Master_Country { get; set; }
        public virtual Master_StaffEducationalDegree Master_StaffEducationalDegree { get; set; }
        public virtual Master_StaffMajorSubject Master_StaffMajorSubject { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
