//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_NarrationInformation
    {
        public System.Guid ID { get; set; }
        public System.Guid StaffID { get; set; }
        public Nullable<long> NoOfExpYear { get; set; }
        public Nullable<long> NoOfExpMonth { get; set; }
        public string OtherExperience_en { get; set; }
        public string OtherExperience_jp { get; set; }
        public string OtherExperience_kr { get; set; }
        public string OtherExperience_cn { get; set; }
        public string OtherExperience_fr { get; set; }
        public string OtherExperience_tl { get; set; }
        public Nullable<long> PricePerWork { get; set; }
        public Nullable<long> PricePerHour { get; set; }
        public Nullable<long> MinPrice { get; set; }
        public Nullable<long> PricePerWorkRequest { get; set; }
        public Nullable<long> PricePerHourRequest { get; set; }
        public Nullable<long> MinPriceRequest { get; set; }
        public Nullable<int> VoiceType { get; set; }
        public Nullable<int> AgeImpression { get; set; }
        public string SceneOrPurposes { get; set; }
        public string VoiceSampleFile1 { get; set; }
        public string VoiceSampleFile2 { get; set; }
        public string VoiceSampleFile3 { get; set; }
        public string SelfPromotion_en { get; set; }
        public string SelfPromotion_jp { get; set; }
        public string SelfPromotion_kr { get; set; }
        public string SelfPromotion_cn { get; set; }
        public string SelfPromotion_fr { get; set; }
        public string SelfPromotion_tl { get; set; }
        public string Coordinator_en { get; set; }
        public string Coordinator_jp { get; set; }
        public string Coordinator_kr { get; set; }
        public string Coordinator_cn { get; set; }
        public string Coordinator_fr { get; set; }
        public string Coordinator_tl { get; set; }
        public Nullable<bool> IsShowWebsite { get; set; }
        public Nullable<bool> IsPartnerNarrator { get; set; }
        public Nullable<bool> IsPromote { get; set; }
        public Nullable<int> PriorityValue { get; set; }
        public Nullable<int> CustomerEvaluation { get; set; }
        public Nullable<int> NarrationLevel { get; set; }
        public Nullable<System.Guid> ProfessionID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
