//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_NarrationVoiceFiles
    {
        public System.Guid ID { get; set; }
        public System.Guid StaffID { get; set; }
        public Nullable<System.Guid> NarrationTypeID { get; set; }
        public string OrderNo { get; set; }
        public string VoiceDetail_en { get; set; }
        public string VoiceDetail_jp { get; set; }
        public string VoiceDetail_kr { get; set; }
        public string VoiceDetail_cn { get; set; }
        public string VoiceDetail_fr { get; set; }
        public string VoiceDetail_tl { get; set; }
        public string NarrationFileName { get; set; }
        public string UploadURL { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
