//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_TranslationSpecialFields
    {
        public System.Guid ID { get; set; }
        public System.Guid StaffID { get; set; }
        public System.Guid TranslationSpecialFieldID { get; set; }
        public bool IsSelected { get; set; }
    
        public virtual Master_StaffTranslationFields Master_StaffTranslationFields { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
