//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.EmailDeliverySettings = new HashSet<EmailDeliverySetting>();
            this.Order_Web = new HashSet<Order_Web>();
            this.OrderAppointedToStaff_Web = new HashSet<OrderAppointedToStaff_Web>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderEvaluationByCustomers = new HashSet<OrderEvaluationByCustomer>();
            this.OrderRequestedToStaff_Web = new HashSet<OrderRequestedToStaff_Web>();
            this.Staff_BankAccountInfo = new HashSet<Staff_BankAccountInfo>();
            this.Staff_CurrentStates = new HashSet<Staff_CurrentStates>();
            this.Staff_DevelopmentSkill = new HashSet<Staff_DevelopmentSkill>();
            this.Staff_EditingproInformation = new HashSet<Staff_EditingproInformation>();
            this.Staff_EducationalHistory = new HashSet<Staff_EducationalHistory>();
            this.Staff_InterpretationSpecialFields = new HashSet<Staff_InterpretationSpecialFields>();
            this.Staff_JobCategories = new HashSet<Staff_JobCategories>();
            this.Staff_JobHistory = new HashSet<Staff_JobHistory>();
            this.Staff_KnowledgeFields = new HashSet<Staff_KnowledgeFields>();
            this.Staff_ManagementExperience = new HashSet<Staff_ManagementExperience>();
            this.Staff_NarrationInformation = new HashSet<Staff_NarrationInformation>();
            this.Staff_NarrationVoiceFiles = new HashSet<Staff_NarrationVoiceFiles>();
            this.Staff_ProfessionalSpeciality = new HashSet<Staff_ProfessionalSpeciality>();
            this.Staff_ServiceTypes = new HashSet<Staff_ServiceTypes>();
            this.Staff_SkillCertificate = new HashSet<Staff_SkillCertificate>();
            this.Staff_TechnicalCertificate = new HashSet<Staff_TechnicalCertificate>();
            this.Staff_TranslateInterpretExperience = new HashSet<Staff_TranslateInterpretExperience>();
            this.Staff_TranslationSpecialFields = new HashSet<Staff_TranslationSpecialFields>();
            this.Staff_TransproInformation = new HashSet<Staff_TransproInformation>();
            this.Staff_SoftwareSkill = new HashSet<Staff_SoftwareSkill>();
        }
    
        public System.Guid ID { get; set; }
        public long RegistrationID { get; set; }
        public string StaffEmailID { get; set; }
        public int StaffTypeID { get; set; }
        public Nullable<long> MyIdentityNo { get; set; }
        public Nullable<long> ApplicationID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string Password { get; set; }
        public string NickName_en { get; set; }
        public string NickName_jp { get; set; }
        public string NickName_kr { get; set; }
        public string NickName_cn { get; set; }
        public string NickName_fr { get; set; }
        public string NickName_tl { get; set; }
        public string Surname { get; set; }
        public string FirstName_en { get; set; }
        public string FirstName_jp { get; set; }
        public string FirstName_kr { get; set; }
        public string FirstName_cn { get; set; }
        public string FirstName_fr { get; set; }
        public string FirstName_tl { get; set; }
        public string MiddleName_en { get; set; }
        public string MiddleName_jp { get; set; }
        public string MiddleName_kr { get; set; }
        public string MiddleName_cn { get; set; }
        public string MiddleName_fr { get; set; }
        public string MiddleName_tl { get; set; }
        public string LastName_en { get; set; }
        public string LastName_jp { get; set; }
        public string LastName_kr { get; set; }
        public string LastName_cn { get; set; }
        public string LastName_fr { get; set; }
        public string LastName_tl { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PostalCode { get; set; }
        public Nullable<bool> IsJapanese { get; set; }
        public Nullable<long> LivingCountryID { get; set; }
        public string CityOfOverseas_en { get; set; }
        public string CityOfOverseas_jp { get; set; }
        public string CityOfOverseas_kr { get; set; }
        public string CityOfOverseas_cn { get; set; }
        public string CityOfOverseas_fr { get; set; }
        public string CityOfOverseas_tl { get; set; }
        public System.Guid NativeLanguageID { get; set; }
        public System.Guid ForiegnLanguage1ID { get; set; }
        public Nullable<System.Guid> ForiegnLanguage2ID { get; set; }
        public Nullable<System.Guid> ForiegnLanguage3ID { get; set; }
        public Nullable<System.Guid> ForiegnLanguage4ID { get; set; }
        public Nullable<int> ForeignLang1Level { get; set; }
        public Nullable<int> ForeignLang2Level { get; set; }
        public Nullable<int> ForeignLang3Level { get; set; }
        public Nullable<int> ForeignLang4Level { get; set; }
        public Nullable<System.Guid> TranslationExpID { get; set; }
        public string OtherLanguage { get; set; }
        public string OtherLangQualification { get; set; }
        public Nullable<System.Guid> VisaTypeID { get; set; }
        public Nullable<System.DateTime> VisaDeadLine { get; set; }
        public string District_en { get; set; }
        public string District_jp { get; set; }
        public string District_kr { get; set; }
        public string District_cn { get; set; }
        public string District_fr { get; set; }
        public string District_tl { get; set; }
        public string TownName_en { get; set; }
        public string TownName_jp { get; set; }
        public string TownName_kr { get; set; }
        public string TownName_cn { get; set; }
        public string TownName_fr { get; set; }
        public string TownName_tl { get; set; }
        public string Address_en { get; set; }
        public string Address_jp { get; set; }
        public string Address_kr { get; set; }
        public string Address_cn { get; set; }
        public string Address_fr { get; set; }
        public string Address_tl { get; set; }
        public string ApartmentName_en { get; set; }
        public string ApartmentName_jp { get; set; }
        public string ApartmentName_kr { get; set; }
        public string ApartmentName_cn { get; set; }
        public string ApartmentName_fr { get; set; }
        public string ApartmentName_tl { get; set; }
        public string ApartmentNo { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string HomeCountryPhone { get; set; }
        public string Fax { get; set; }
        public string HomeCountryAddress_en { get; set; }
        public string HomeCountryAddress_jp { get; set; }
        public string HomeCountryAddress_kr { get; set; }
        public string HomeCountryAddress_cn { get; set; }
        public string HomeCountryAddress_fr { get; set; }
        public string HomeCountryAddress_tl { get; set; }
        public Nullable<bool> HasSocialExperienceJapan { get; set; }
        public Nullable<bool> HasSocialExperienceOtherCountry { get; set; }
        public string IntroductionVideoURL { get; set; }
        public string Street_en { get; set; }
        public string Street_jp { get; set; }
        public string Street_kr { get; set; }
        public string Street_cn { get; set; }
        public string Street_fr { get; set; }
        public string Street_tl { get; set; }
        public Nullable<System.Guid> EducationalDegree1 { get; set; }
        public Nullable<System.Guid> EducationalDegree2 { get; set; }
        public Nullable<System.Guid> EducationalDegree3 { get; set; }
        public string MainCareer_en { get; set; }
        public string MainCareer_jp { get; set; }
        public string MainCareer_kr { get; set; }
        public string MainCareer_cn { get; set; }
        public string MainCareer_fr { get; set; }
        public string MainCareer_tl { get; set; }
        public string SelfPR_en { get; set; }
        public string SelfPR_jp { get; set; }
        public string SelfPR_kr { get; set; }
        public string SelfPR_cn { get; set; }
        public string SelfPR_fr { get; set; }
        public string SelfPR_tl { get; set; }
        public string BankName { get; set; }
        public string BankBranchName { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountType { get; set; }
        public string IntroducedBy { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string Image { get; set; }
        public string StaffNo { get; set; }
        public Nullable<long> CountryOfCitizenship { get; set; }
        public string NationalityID { get; set; }
        public bool IsDeleted { get; set; }
        public string SelfVideoURL { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailDeliverySetting> EmailDeliverySettings { get; set; }
        public virtual Master_Country Master_Country { get; set; }
        public virtual Master_Language Master_Language { get; set; }
        public virtual Master_Language Master_Language1 { get; set; }
        public virtual Master_Language Master_Language2 { get; set; }
        public virtual Master_Language Master_Language3 { get; set; }
        public virtual Master_Language Master_Language4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Web> Order_Web { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderAppointedToStaff_Web> OrderAppointedToStaff_Web { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderEvaluationByCustomer> OrderEvaluationByCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRequestedToStaff_Web> OrderRequestedToStaff_Web { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_BankAccountInfo> Staff_BankAccountInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_CurrentStates> Staff_CurrentStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_DevelopmentSkill> Staff_DevelopmentSkill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_EditingproInformation> Staff_EditingproInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_EducationalHistory> Staff_EducationalHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_InterpretationSpecialFields> Staff_InterpretationSpecialFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_JobCategories> Staff_JobCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_JobHistory> Staff_JobHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_KnowledgeFields> Staff_KnowledgeFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_ManagementExperience> Staff_ManagementExperience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_NarrationInformation> Staff_NarrationInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_NarrationVoiceFiles> Staff_NarrationVoiceFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_ProfessionalSpeciality> Staff_ProfessionalSpeciality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_ServiceTypes> Staff_ServiceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_SkillCertificate> Staff_SkillCertificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_TechnicalCertificate> Staff_TechnicalCertificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_TranslateInterpretExperience> Staff_TranslateInterpretExperience { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_TranslationSpecialFields> Staff_TranslationSpecialFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_TransproInformation> Staff_TransproInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_SoftwareSkill> Staff_SoftwareSkill { get; set; }
    }
}
