//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_EditingproInformation
    {
        public System.Guid ID { get; set; }
        public System.Guid StaffID { get; set; }
        public Nullable<long> OverallScore { get; set; }
        public Nullable<long> InternalScore { get; set; }
        public Nullable<int> NumberOfWorks { get; set; }
        public Nullable<long> FavoritePoint { get; set; }
        public Nullable<long> CustomerEvaluationPoint { get; set; }
        public Nullable<long> PenaltyPoint { get; set; }
        public Nullable<long> NegativePoint { get; set; }
        public Nullable<System.DateTime> BannedPeriodFrom { get; set; }
        public Nullable<System.DateTime> BannedPeriodTo { get; set; }
        public string CustomerEvaluation_en { get; set; }
        public string CustomerEvaluation_jp { get; set; }
        public string CustomerEvaluation_kr { get; set; }
        public string CustomerEvaluation_cn { get; set; }
        public string CustomerEvaluation_fr { get; set; }
        public string CustomerEvaluation_tl { get; set; }
        public Nullable<bool> IsExpertCertified { get; set; }
        public Nullable<System.DateTime> LastEvaluationDate { get; set; }
        public Nullable<System.DateTime> NextEvaluationDate { get; set; }
        public string EvaluationHistory { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
