//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_SoftwareSkill
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> StaffID { get; set; }
        public Nullable<long> StaffSoftwareSkillID { get; set; }
        public Nullable<bool> IsSelected { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual Master_StaffSoftwareSkill Master_StaffSoftwareSkill { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
