//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_ManagementExperience
    {
        public System.Guid ID { get; set; }
        public System.Guid StaffID { get; set; }
        public Nullable<int> ManagementExperienceID { get; set; }
        public Nullable<System.DateTime> Project1StartDate { get; set; }
        public Nullable<System.DateTime> Project1EndDate { get; set; }
        public string Project1CompanyName_en { get; set; }
        public string Project1CompanyName_jp { get; set; }
        public string Project1CompanyName_kr { get; set; }
        public string Project1CompanyName_cn { get; set; }
        public string Project1CompanyName_fr { get; set; }
        public string Project1CompanyName_tl { get; set; }
        public string Project1SystemName_en { get; set; }
        public string Project1SystemName_jp { get; set; }
        public string Project1SystemName_kr { get; set; }
        public string Project1SystemName_cn { get; set; }
        public string Project1SystemName_fr { get; set; }
        public string Project1SystemName_tl { get; set; }
        public string Project1Language { get; set; }
        public Nullable<int> Project1ResponsibleRoleID { get; set; }
        public Nullable<System.DateTime> Project2StartDate { get; set; }
        public Nullable<System.DateTime> Project2EndDate { get; set; }
        public string Project2CompanyName_en { get; set; }
        public string Project2CompanyName_jp { get; set; }
        public string Project2CompanyName_kr { get; set; }
        public string Project2CompanyName_cn { get; set; }
        public string Project2CompanyName_fr { get; set; }
        public string Project2CompanyName_tl { get; set; }
        public string Project2SystemName_en { get; set; }
        public string Project2SystemName_jp { get; set; }
        public string Project2SystemName_kr { get; set; }
        public string Project2SystemName_cn { get; set; }
        public string Project2SystemName_fr { get; set; }
        public string Project2SystemName_tl { get; set; }
        public string Project2Language { get; set; }
        public Nullable<int> Project2ResponsibleRoleID { get; set; }
        public string DevelopmentExperienceIDs { get; set; }
        public string Comments_en { get; set; }
        public string Comments_jp { get; set; }
        public string Comments_kr { get; set; }
        public string Comments_cn { get; set; }
        public string Comments_fr { get; set; }
        public string Comments_tl { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
