//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_tbd
    {
        public long RegistrationID { get; set; }
        public string StaffEmailID { get; set; }
        public string NickName_en { get; set; }
        public string NickName_jp { get; set; }
        public string NickName_kr { get; set; }
        public string NickName_cn { get; set; }
        public string NickName_fr { get; set; }
        public string NickName_tl { get; set; }
        public string FirstName_en { get; set; }
        public string FirstName_jp { get; set; }
        public string FirstName_kr { get; set; }
        public string FirstName_cn { get; set; }
        public string FirstName_fr { get; set; }
        public string FirstName_tl { get; set; }
        public string MiddleName_en { get; set; }
        public string MiddleName_jp { get; set; }
        public string MiddleName_kr { get; set; }
        public string MiddleName_cn { get; set; }
        public string MiddleName_fr { get; set; }
        public string MiddleName_tl { get; set; }
        public string LastName_en { get; set; }
        public string LastName_jp { get; set; }
        public string LastName_kr { get; set; }
        public string LastName_cn { get; set; }
        public string LastName_fr { get; set; }
        public string LastName_tl { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string Fax { get; set; }
        public System.Guid ForiegnLanguage1ID { get; set; }
        public string Expr39 { get; set; }
        public string Expr40 { get; set; }
        public string Expr41 { get; set; }
        public string Expr42 { get; set; }
        public string Expr43 { get; set; }
        public string Expr44 { get; set; }
        public string Expr45 { get; set; }
        public bool Expr46 { get; set; }
        public Nullable<int> ForeignLang1Level { get; set; }
        public Nullable<System.Guid> ForiegnLanguage2ID { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
        public string Expr5 { get; set; }
        public string Expr6 { get; set; }
        public string Expr7 { get; set; }
        public bool Expr8 { get; set; }
        public Nullable<int> ForeignLang2Level { get; set; }
        public Nullable<System.Guid> ForiegnLanguage3ID { get; set; }
        public string Expr9 { get; set; }
        public string Expr10 { get; set; }
        public string Expr11 { get; set; }
        public string Expr12 { get; set; }
        public string Expr13 { get; set; }
        public string Expr14 { get; set; }
        public string Expr15 { get; set; }
        public bool Expr16 { get; set; }
        public Nullable<int> ForeignLang3Level { get; set; }
        public Nullable<System.Guid> ForiegnLanguage4ID { get; set; }
        public string Expr17 { get; set; }
        public string Expr18 { get; set; }
        public string Expr19 { get; set; }
        public string Expr20 { get; set; }
        public string Expr21 { get; set; }
        public string Expr22 { get; set; }
        public string Expr23 { get; set; }
        public bool Expr24 { get; set; }
        public Nullable<int> ForeignLang4Level { get; set; }
        public bool Sex { get; set; }
        public System.DateTime BirthDate { get; set; }
        public long CountryOfCitizenship { get; set; }
        public string Expr25 { get; set; }
        public string Expr26 { get; set; }
        public string Expr27 { get; set; }
        public string Expr28 { get; set; }
        public string Expr29 { get; set; }
        public string Expr30 { get; set; }
        public string Expr31 { get; set; }
        public Nullable<bool> IsTrading { get; set; }
        public Nullable<int> SortBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> LivingCountryID { get; set; }
        public string Code { get; set; }
        public string Name_en { get; set; }
        public string Name_jp { get; set; }
        public string Name_kr { get; set; }
        public string Name_cn { get; set; }
        public string Name_fr { get; set; }
        public string Name_tl { get; set; }
        public Nullable<bool> Expr32 { get; set; }
        public Nullable<int> Expr33 { get; set; }
        public bool Expr34 { get; set; }
        public System.Guid VisaTypeID { get; set; }
        public string Expr35 { get; set; }
        public string Expr36 { get; set; }
        public string Expr37 { get; set; }
        public string Expr38 { get; set; }
        public string Expr47 { get; set; }
        public string Expr48 { get; set; }
        public string Description_en { get; set; }
        public string Description_jp { get; set; }
        public string Description_kr { get; set; }
        public string Description_cn { get; set; }
        public string Description_fr { get; set; }
        public string Description_tl { get; set; }
        public Nullable<int> Expr49 { get; set; }
        public bool Expr50 { get; set; }
    }
}
