//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_SkillCertificate
    {
        public System.Guid ID { get; set; }
        public System.Guid StaffID { get; set; }
        public Nullable<System.Guid> MainLanguageID { get; set; }
        public Nullable<int> MainLanguageLevelID { get; set; }
        public Nullable<System.Guid> FoeignLanguageID1 { get; set; }
        public Nullable<System.Guid> FoeignLanguageID2 { get; set; }
        public Nullable<System.Guid> FoeignLanguageID3 { get; set; }
        public Nullable<int> ForeignLanguageLevelID1 { get; set; }
        public Nullable<int> ForeignLanguageLevelID2 { get; set; }
        public Nullable<int> ForeignLanguageLevelID3 { get; set; }
        public Nullable<long> TOEICScore { get; set; }
        public Nullable<System.DateTime> TOEICDate { get; set; }
        public Nullable<long> TOFELScore { get; set; }
        public Nullable<System.DateTime> TOFELDate { get; set; }
        public string CertificateName1 { get; set; }
        public string CertificateName2 { get; set; }
        public string CertificateName3 { get; set; }
        public Nullable<System.DateTime> CertificateDate1 { get; set; }
        public Nullable<System.DateTime> CertificateDate2 { get; set; }
        public Nullable<System.DateTime> CertificateDate3 { get; set; }
        public Nullable<System.Guid> SpecialField1 { get; set; }
        public Nullable<System.Guid> SpecialField2 { get; set; }
        public Nullable<System.Guid> SpecialField3 { get; set; }
        public Nullable<System.Guid> SpecialField4 { get; set; }
        public Nullable<System.Guid> SpecialField5 { get; set; }
        public string Comment_en { get; set; }
        public string Comment_jp { get; set; }
        public string Comment_kr { get; set; }
        public string Comment_cn { get; set; }
        public string Comment_fr { get; set; }
        public string Comment_tl { get; set; }
        public Nullable<System.DateTime> Project1StartDate { get; set; }
        public Nullable<System.DateTime> Project1EndDate { get; set; }
        public Nullable<int> Project1TeamSize { get; set; }
        public Nullable<long> Project1Budget { get; set; }
        public string Project1CompanyName_en { get; set; }
        public string Project1CompanyName_jp { get; set; }
        public string Project1CompanyName_kr { get; set; }
        public string Project1CompanyName_cn { get; set; }
        public string Project1CompanyName_fr { get; set; }
        public string Project1CompanyName_tl { get; set; }
        public string Project1Role_en { get; set; }
        public string Project1Role_jp { get; set; }
        public string Project1Role_kr { get; set; }
        public string Project1Role_cn { get; set; }
        public string Project1Role_fr { get; set; }
        public string Project1Role_tl { get; set; }
        public Nullable<System.DateTime> Project2StartDate { get; set; }
        public Nullable<System.DateTime> Project2EndDate { get; set; }
        public Nullable<int> Project2TeamSize { get; set; }
        public Nullable<long> Project2Budget { get; set; }
        public string Project2CompanyName_en { get; set; }
        public string Project2CompanyName_jp { get; set; }
        public string Project2CompanyName_kr { get; set; }
        public string Project2CompanyName_cn { get; set; }
        public string Project2CompanyName_fr { get; set; }
        public string Project2CompanyName_tl { get; set; }
        public string Project2Role_en { get; set; }
        public string Project2Role_jp { get; set; }
        public string Project2Role_kr { get; set; }
        public string Project2Role_cn { get; set; }
        public string Project2Role_fr { get; set; }
        public string Project2Role_tl { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        public virtual Master_Language Master_Language { get; set; }
        public virtual Master_Language Master_Language1 { get; set; }
        public virtual Master_Language Master_Language2 { get; set; }
        public virtual Master_Language Master_Language3 { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
