//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_KnowledgeFields
    {
        public System.Guid ID { get; set; }
        public System.Guid StaffID { get; set; }
        public System.Guid KnowledgeFieldID { get; set; }
        public System.Guid KnowledgeFieldItemID { get; set; }
        public Nullable<bool> IsSelected { get; set; }
    
        public virtual Master_StaffKnowledgeField Master_StaffKnowledgeField { get; set; }
        public virtual Master_StaffKnowledgeFieldItem Master_StaffKnowledgeFieldItem { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
