//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_DevelopmentSkill
    {
        public System.Guid ID { get; set; }
        public System.Guid StaffID { get; set; }
        public System.Guid DevelopmentSkillID { get; set; }
        public System.Guid DevelopmentSkillItemID { get; set; }
        public Nullable<int> ExperienceInYears { get; set; }
    
        public virtual Master_StaffDevelopmentSkill Master_StaffDevelopmentSkill { get; set; }
        public virtual Master_StaffDevelopmentSkillItem Master_StaffDevelopmentSkillItem { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
