//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslatorBlackList
    {
        public System.Guid ID { get; set; }
        public System.Guid ClientID { get; set; }
        public System.Guid StaffID { get; set; }
    }
}
