//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransproLanguagePriceDetail
    {
        public System.Guid ID { get; set; }
        public System.Guid PriceCategoryID { get; set; }
        public long DeliveryPlanID { get; set; }
        public Nullable<decimal> LightPrice { get; set; }
        public Nullable<decimal> BusinessPrice { get; set; }
        public Nullable<decimal> ExpertPrice { get; set; }
        public bool IsDefaultForView { get; set; }
        public Nullable<int> SortBy { get; set; }
    
        public virtual TransproDeliveryPlanSetting TransproDeliveryPlanSetting { get; set; }
        public virtual TransproLanguagePriceCategory TransproLanguagePriceCategory { get; set; }
    }
}
