//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiWork.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransproLanguagePriceSetting
    {
        public System.Guid ID { get; set; }
        public System.Guid SourceLanguageID { get; set; }
        public System.Guid TargetLanguageID { get; set; }
        public Nullable<System.Guid> SpecializedFieldID { get; set; }
        public Nullable<long> DeliveryTypeID { get; set; }
        public Nullable<decimal> LightPrice { get; set; }
        public Nullable<decimal> BusinessPrice { get; set; }
        public Nullable<decimal> ExpertPrice { get; set; }
        public Nullable<long> SrcLanguageWordUnit { get; set; }
        public Nullable<long> CurrencyID { get; set; }
        public string Comment_en { get; set; }
        public string Comment_jp { get; set; }
        public string Comment_kr { get; set; }
        public string Comment_cn { get; set; }
        public string Comment_fr { get; set; }
        public string Comment_tl { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Master_Currency Master_Currency { get; set; }
        public virtual Master_EstimationSpecializedField Master_EstimationSpecializedField { get; set; }
        public virtual Master_Language Master_Language { get; set; }
        public virtual Master_Language Master_Language1 { get; set; }
        public virtual TransproDeliveryPlanSetting TransproDeliveryPlanSetting { get; set; }
    }
}
